language: android
sudo: false
android:
  components:
  - tools
  - android-25
  - platform-tools
  - build-tools-25.0.2
  - extra-android-m2repository
  - extra-android-support
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  - openssl aes-256-cbc -K $encrypted_9fa0e1157a33_key -iv $encrypted_9fa0e1157a33_iv -in seed.jks.enc -out seed.jks -d
  - gem install fir-cli
script: ./gradlew build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: uJpVILpxz1xsPtKDwDfNvuYcFNkkkBDxIVOT4SSL3gIX7fpONcp6XyZfRGZA7sOcxOKu6Psz6aoITdIUw1nX+kcyTsNXVxPuSYDH0flLLYMttz537jaM6YqvP/GK7lP9E3w+wCpYE/hdcC83wEuZeRxS+7yHIHn971AqDrI6b4snVzpoJCNzaENyRuGlPpf0OkkE8m/0tiwQllEnTv3nP82CY+pYS5mAyHLo3NvBGQ6VikWi3g7r3TtApg/oBPzzK9aIhAXR6dD7iQIfbfvmwoXFVGdmwsSOn21haTGjk4RrEfLZEKhooUbXRjPZcx3glsywc3PjSu2J9jsTDNd4EmtaAU8rPTDDzqGMvupBsGrvRle+D6hIwimwv8CCcHdWubPxr3J2Lz4EE4PmHkkpaZwefE7PssTzLLxQLMfvK2vEEeOYvqv3L1+rDQ5NDZGTnkD77sJceeZyBu73Jzt7GZLGmnU8Zrqx/7wYB18SoiJHdYb4CzH6nlQBPxIcDL4jcJb47CO6EqNeQDiY/LVVw74VxqytfDAysi4xMjbZhQqbl+AV8FSala+Q58pAjqd4OsSFtABrB1IUwvIM+a92vrbY3RR0xWURZjLsRzANY2iPE8YeVcRJzpRaRYkODeGeSF4LVRG5tT22PCvAdbXpcBmSRuwk6PzdKZdp8WCerIE=
  file: app/build/outputs/apk/app-github-release.apk
  on:
    tags: true
    all_branches: true
after_deploy:
- fir p app/build/outputs/apk/app-github-release.apk -T $FIR_TOKEN -c "`git cat-file
  tag $TRAVIS_TAG`"
